version: '3'
services:
  nodejs:
    image: node:18-alpine
    build: .
    networks:
      - find_my_meal_network
    volumes:
      - ./src/:/app
  
  mysql:
    image: mysql:8.1-oracle
    environment:
      - MYSQL_USER=custom_user
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=find_my_meal_console
    networks:
      - find_my_meal_network
    ports:
      - 3307:3306

networks:
  find_my_meal_network: